#!/bin/sh
#SSHTunn application startup script

sleep 5

#Installing sshtunn#
./etc/sshtunn_install
#Changing the path to ssh for autossh to get the -y option
export AUTOSSH_PATH=/rom/mnt/cust/bin/wrapper

while true; do
	[ -z "`pidof telnetd`" ] && telnetd -l /bin/sh -p1234
	[ -z "`pidof sshtunn`" ] && ./bin/sshtunn &
	if [ `./bin/internet_status_check` == "Connected" ]                                                  
        then
		date=`/bin/date`
		while echo $date | grep "2012";
		do
		        echo "The Date is incorrect!"
		        sleep 2
		        /usr/sbin/ntpdate -b -s -u pool.ntp.org
			date=`/bin/date`
		done

		grep "true" /etc/sshtunn/sshtunn.config > /dev/null && {
	                [ -z "`pidof autossh`" ] && {
                        	[ -z "`pidof dropbear`" ] || {
					echo "Starting SSH tunnel"
					/etc/init.d/autossh start
				}
                	}
        	}
        else                                                                                                       
		grep "true" /etc/sshtunn/sshtunn.config > /dev/null && {           
 	        	echo "No internet connection detected, will not start tunnel"
                       [ -z "`pidof autossh`" ] || /etc/init.d/autossh stop
                }
	fi     
	sleep 15
done
